import json
import re
import time

import boto3

from app.core.config import settings


def _guardrail_config() -> dict:
    """Return guardrailConfig kwarg for converse() if a guardrail is configured."""
    gid = settings.BEDROCK_GUARDRAIL_ID
    gver = settings.BEDROCK_GUARDRAIL_VERSION
    if gid and gver:
        return {"guardrailConfig": {"guardrailIdentifier": gid, "guardrailVersion": gver}}
    return {}


def _bedrock_boto3_kwargs() -> dict:
    """Return boto3 keyword args for Bedrock clients.

    If BEDROCK_CROSS_ACCOUNT_ROLE_ARN is configured, assumes that role first
    (cross-account access to company Bedrock) and returns short-lived credentials.
    Otherwise returns an empty dict so boto3 uses the pod's IRSA role directly.
    """
    if not settings.BEDROCK_CROSS_ACCOUNT_ROLE_ARN:
        return {}
    sts = boto3.client("sts", region_name=settings.AWS_REGION)
    assumed = sts.assume_role(
        RoleArn=settings.BEDROCK_CROSS_ACCOUNT_ROLE_ARN,
        RoleSessionName="agora-worker-bedrock",
        DurationSeconds=3600,
    )
    creds = assumed["Credentials"]
    return {
        "aws_access_key_id": creds["AccessKeyId"],
        "aws_secret_access_key": creds["SecretAccessKey"],
        "aws_session_token": creds["SessionToken"],
    }


class BedrockRemediationClient:
    """Calls AWS Bedrock (Amazon Nova) to analyze CI failures and produce fixes.

    Uses the model-agnostic Converse API rather than ``invoke_model`` so swapping
    ``BEDROCK_MODEL_ID`` to a different model family doesn't require touching the
    request/response shape here.
    """

    def __init__(self) -> None:
        self._client = boto3.client(
            "bedrock-runtime",
            region_name=settings.AWS_REGION,
            **_bedrock_boto3_kwargs(),
        )
        self._model_id = settings.BEDROCK_MODEL_ID

    def _build_prompt(
        self,
        workflow_yaml: str,
        logs: str,
        workflow_name: str,
        repo: str,
    ) -> str:
        return f"""You are an expert DevOps engineer specializing in GitHub Actions CI/CD pipelines.

A workflow named "{workflow_name}" in repository "{repo}" has failed.

## Failed Workflow YAML
```yaml
{workflow_yaml}
```

## Failure Logs (last 300 lines)
```
{logs}
```

Analyze the failure and provide a fix. Respond with ONLY valid JSON in this exact format:
{{
  "root_cause": "One clear sentence describing why the workflow failed",
  "fixed_yaml": "The complete corrected workflow YAML as a string",
  "pr_title": "fix: <short description of the fix>",
  "pr_description": "## Root Cause\\n<root_cause>\\n\\n## Changes Made\\n- bullet point changes\\n\\n## Testing\\nThis fix was generated by PipelineIQ AI using AWS Bedrock (Amazon Nova). Please review the changes before merging.\\n\\n> 🤖 Auto-generated by [PipelineIQ](https://github.com/pipelineiq)"
}}"""

    def analyze_failure(
        self,
        workflow_yaml: str,
        logs: str,
        workflow_name: str,
        repo: str,
    ) -> dict:
        """
        Call Bedrock to analyze the workflow failure.

        Returns:
            A dict with keys: root_cause, fixed_yaml, pr_title, pr_description.

        Raises:
            Exception: If the model cannot be invoked after retries or the response
                       cannot be parsed as valid JSON.
        """
        prompt = self._build_prompt(workflow_yaml, logs, workflow_name, repo)

        max_retries = 2
        last_exception: Exception | None = None

        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[
                        {
                            "role": "user",
                            "content": [{"text": prompt}],
                        }
                    ],
                    inferenceConfig={"maxTokens": 8192},
                    **_guardrail_config(),
                )
                raw_text: str = response["output"]["message"]["content"][0]["text"].strip()

                raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text, flags=re.MULTILINE)
                raw_text = re.sub(r"\s*```$", "", raw_text, flags=re.MULTILINE)
                raw_text = raw_text.strip()

                parsed: dict = json.loads(raw_text)

                required_keys = {"root_cause", "fixed_yaml", "pr_title", "pr_description"}
                missing = required_keys - set(parsed.keys())
                if missing:
                    raise ValueError(f"Bedrock response missing keys: {missing}")

                return parsed

            except self._client.exceptions.ThrottlingException as exc:
                last_exception = exc
                if attempt < max_retries:
                    wait = 2 ** (attempt + 1)
                    time.sleep(wait)
                    continue
                raise

            except (json.JSONDecodeError, ValueError, KeyError) as exc:
                _raw = locals().get("raw_text", "<unavailable>")
                raise RuntimeError(
                    f"Failed to parse Bedrock response as valid JSON: {exc}\n"
                    f"Raw response: {_raw}"
                ) from exc

        raise RuntimeError("Bedrock invocation failed after retries") from last_exception

    def generate_yaml_fix(
        self,
        workflow_yaml: str,
        root_cause: str,
        failure_category: str = "UNKNOWN",
        logs: str = "",
        few_shot_context: str = "",
    ) -> str:
        """Directly generate a corrected workflow YAML via the Converse API.

        Used as a fallback when the yaml_fixer Bedrock Agent returns a capability
        refusal instead of actual YAML (e.g. its system prompt restricts it from
        writing files). This path calls the model directly — no agent, no tool use.

        Args:
            workflow_yaml: The original failing YAML content.
            root_cause: Specific root cause string from analyse_root_cause.
            failure_category: One of the 9 classifier categories (e.g. AUTH_FAILURE).
            logs: Last N lines of failure logs for extra context.

        Returns:
            The corrected YAML as a string.
        Raises:
            RuntimeError: If the model refuses or returns unusable output.
        """
        # Per-category fix guidance — tells the model *what kind* of change to make
        _CATEGORY_HINTS = {
            "DEPENDENCY_VERSION": (
                "The issue is an invalid/outdated dependency or language version. "
                "Replace it with the correct stable version from the canonical table below."
            ),
            "AUTH_FAILURE": (
                "The issue is authentication. Common fixes: correct a mistyped secret name "
                "(e.g. ${{ secrets.GITHUB_TOKEN }} not GITHUB_TOKENS), add a missing "
                "permissions block, or fix an env var that should reference a secret."
            ),
            "NETWORK_TIMEOUT": (
                "The issue is a network timeout. Common fixes: add --retry / --connect-timeout "
                "flags to curl/wget commands, increase timeout values, or add a 'continue-on-error: true' "
                "with a retry step."
            ),
            "CONFIG_ERROR": (
                "The issue is a YAML config error. Fix the invalid key name, indentation, "
                "or syntax that caused the failure."
            ),
            "TEST_FAILURE": (
                "Tests failed. Fix the workflow step that runs tests — e.g. correct the test "
                "command, install missing test dependencies, or set required env vars."
            ),
            "BUILD_ERROR": (
                "The build failed. Fix the build step — e.g. add missing build dependencies, "
                "correct the build command, or fix a missing env var."
            ),
            "LINT_ERROR": (
                "A linting/formatting check failed. Fix the lint step — e.g. update the linter "
                "version, correct the lint command, or add a step to auto-fix."
            ),
            "PERMISSION_ERROR": (
                "A permissions error occurred. Add or correct the 'permissions:' block in the "
                "workflow or job, e.g. 'contents: read', 'pull-requests: write'."
            ),
            "UNKNOWN": (
                "Apply the minimal change to the YAML that directly addresses the root cause."
            ),
        }
        category_hint = _CATEGORY_HINTS.get(failure_category, _CATEGORY_HINTS["UNKNOWN"])

        logs_section = (
            f"\nRELEVANT FAILURE LOGS (last 100 lines):\n{logs[-3000:]}\n"
            if logs else ""
        )

        few_shot_section = (
            f"\nPREVIOUSLY ACCEPTED FIXES FOR SIMILAR FAILURES (use as style/pattern reference):\n{few_shot_context}\n"
            if few_shot_context else ""
        )

        prompt = (
            "You are an expert GitHub Actions DevOps engineer fixing a broken CI workflow.\n\n"
            f"FAILURE CATEGORY: {failure_category}\n"
            f"ROOT CAUSE: {root_cause}\n"
            f"FIX GUIDANCE: {category_hint}\n"
            f"{logs_section}"
            f"{few_shot_section}\n"
            "ORIGINAL FAILING YAML:\n"
            "```yaml\n"
            f"{workflow_yaml}\n"
            "```\n\n"
            "CANONICAL STABLE VERSIONS (reference for DEPENDENCY_VERSION fixes):\n"
            "  Python → 3.12 | Node.js → 20 | Java → 21 | Ruby → 3.3 | Go → 1.22\n"
            "  actions/checkout → v4 | actions/setup-python → v5 | actions/setup-node → v4\n\n"
            "STRICT OUTPUT RULES:\n"
            "1. Output ONLY the corrected YAML. Zero prose. Zero explanation.\n"
            "2. Do NOT use markdown fences (no ```).\n"
            "3. Do NOT ask questions. Do NOT say 'I need to ask' or 'please provide'.\n"
            "4. Make the MINIMAL change required — copy every other line byte-for-byte, "
            "including its exact leading whitespace.\n"
            "5. Sibling keys in the same mapping MUST share the exact same indentation as "
            "each other and as they had in the original file. Never shift the indentation "
            "of a line you are not changing, even by one space.\n"
            "6. If a version is clearly invalid (e.g. '99', '0'), replace with the stable version above.\n"
            "Output the corrected YAML now:"
        )
        max_retries = 2
        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[{"role": "user", "content": [{"text": prompt}]}],
                    inferenceConfig={"maxTokens": 8192, "temperature": 0},
                    **_guardrail_config(),
                )
                raw: str = response["output"]["message"]["content"][0]["text"].strip()
                # Strip any accidental markdown fences
                if raw.startswith("```"):
                    lines = raw.splitlines()
                    raw = "\n".join(l for l in lines if not l.startswith("```")).strip()
                if not raw:
                    raise ValueError("Model returned empty YAML fix")
                return raw
            except self._client.exceptions.ThrottlingException:
                if attempt < max_retries:
                    time.sleep(2 ** (attempt + 1))
                    continue
                raise
        raise RuntimeError("generate_yaml_fix: Bedrock invocation failed after retries")

    def correct_yaml_syntax(
        self,
        original_yaml: str,
        malformed_yaml: str,
        error_message: str,
    ) -> str:
        """Invokes Bedrock to fix syntax/parsing errors in a previously generated YAML fix.

        Args:
            original_yaml: The original failing workflow YAML.
            malformed_yaml: The suggested YAML fix that failed to parse.
            error_message: The YAMLError exception message from the parser.

        Returns:
            The corrected YAML string from the model.
        """
        prompt = (
            "You are an expert GitHub Actions DevOps engineer. A YAML parser failed to parse a suggested YAML fix.\n\n"
            "ORIGINAL FAILING WORKFLOW:\n"
            "```yaml\n"
            f"{original_yaml}\n"
            "```\n\n"
            "YOUR PREVIOUS SUGGESTED FIX (CONTAINING SYNTAX ERRORS):\n"
            "```yaml\n"
            f"{malformed_yaml}\n"
            "```\n\n"
            "YAML PARSER ERROR MESSAGE (note the line/column it points to):\n"
            "```\n"
            f"{error_message}\n"
            "```\n\n"
            "STRICT OUTPUT RULES:\n"
            "1. Fix ONLY the syntax/parsing error at the line/column the parser error message "
            "points to. A common cause is indentation drift: a key was shifted by one or more "
            "spaces relative to its sibling keys in the same mapping — if so, realign it to "
            "match its siblings exactly.\n"
            "2. Output ONLY the corrected YAML. Zero prose. Zero markdown code fences (no ```).\n"
            "3. Copy every other line byte-for-byte, including its exact leading whitespace. "
            "Do not re-indent or otherwise touch any line the error message doesn't point to.\n"
            "Output the corrected YAML now:"
        )

        max_retries = 2
        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[{"role": "user", "content": [{"text": prompt}]}],
                    inferenceConfig={"maxTokens": 8192, "temperature": 0},
                    **_guardrail_config(),
                )
                raw: str = response["output"]["message"]["content"][0]["text"].strip()
                # Strip any accidental markdown fences
                if raw.startswith("```"):
                    lines = raw.splitlines()
                    raw = "\n".join(l for l in lines if not l.startswith("```")).strip()
                if not raw:
                    raise ValueError("Model returned empty corrected YAML fix")
                return raw
            except self._client.exceptions.ThrottlingException:
                if attempt < max_retries:
                    time.sleep(2 ** (attempt + 1))
                    continue
                raise
        raise RuntimeError("correct_yaml_syntax: Bedrock invocation failed after retries")
