import json
import re
import time

import boto3

from app.core.config import settings


def _bedrock_boto3_kwargs() -> dict:
    """Return boto3 keyword args for Bedrock clients.

    If BEDROCK_CROSS_ACCOUNT_ROLE_ARN is configured, assumes that role first
    (cross-account access to company Bedrock) and returns short-lived credentials.
    Otherwise returns an empty dict so boto3 uses the pod's IRSA role directly.
    """
    if not settings.BEDROCK_CROSS_ACCOUNT_ROLE_ARN:
        return {}
    sts = boto3.client("sts", region_name=settings.AWS_REGION)
    assumed = sts.assume_role(
        RoleArn=settings.BEDROCK_CROSS_ACCOUNT_ROLE_ARN,
        RoleSessionName="agora-worker-bedrock",
        DurationSeconds=3600,
    )
    creds = assumed["Credentials"]
    return {
        "aws_access_key_id": creds["AccessKeyId"],
        "aws_secret_access_key": creds["SecretAccessKey"],
        "aws_session_token": creds["SessionToken"],
    }


class BedrockRemediationClient:
    """Calls AWS Bedrock (Amazon Nova) to analyze CI failures and produce fixes.

    Uses the model-agnostic Converse API rather than ``invoke_model`` so swapping
    ``BEDROCK_MODEL_ID`` to a different model family doesn't require touching the
    request/response shape here.
    """

    def __init__(self) -> None:
        self._client = boto3.client(
            "bedrock-runtime",
            region_name=settings.AWS_REGION,
            **_bedrock_boto3_kwargs(),
        )
        self._model_id = settings.BEDROCK_MODEL_ID

    def _build_prompt(
        self,
        workflow_yaml: str,
        logs: str,
        workflow_name: str,
        repo: str,
    ) -> str:
        return f"""You are an expert DevOps engineer specializing in GitHub Actions CI/CD pipelines.

A workflow named "{workflow_name}" in repository "{repo}" has failed.

## Failed Workflow YAML
```yaml
{workflow_yaml}
```

## Failure Logs (last 300 lines)
```
{logs}
```

Analyze the failure and provide a fix. Respond with ONLY valid JSON in this exact format:
{{
  "root_cause": "One clear sentence describing why the workflow failed",
  "fixed_yaml": "The complete corrected workflow YAML as a string",
  "pr_title": "fix: <short description of the fix>",
  "pr_description": "## Root Cause\\n<root_cause>\\n\\n## Changes Made\\n- bullet point changes\\n\\n## Testing\\nThis fix was generated by PipelineIQ AI using AWS Bedrock (Amazon Nova). Please review the changes before merging.\\n\\n> 🤖 Auto-generated by [PipelineIQ](https://github.com/pipelineiq)"
}}"""

    def analyze_failure(
        self,
        workflow_yaml: str,
        logs: str,
        workflow_name: str,
        repo: str,
    ) -> dict:
        """
        Call Bedrock to analyze the workflow failure.

        Returns:
            A dict with keys: root_cause, fixed_yaml, pr_title, pr_description.

        Raises:
            Exception: If the model cannot be invoked after retries or the response
                       cannot be parsed as valid JSON.
        """
        prompt = self._build_prompt(workflow_yaml, logs, workflow_name, repo)

        max_retries = 2
        last_exception: Exception | None = None

        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[
                        {
                            "role": "user",
                            "content": [{"text": prompt}],
                        }
                    ],
                    inferenceConfig={"maxTokens": 8192},
                )
                raw_text: str = response["output"]["message"]["content"][0]["text"].strip()

                raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text, flags=re.MULTILINE)
                raw_text = re.sub(r"\s*```$", "", raw_text, flags=re.MULTILINE)
                raw_text = raw_text.strip()

                parsed: dict = json.loads(raw_text)

                required_keys = {"root_cause", "fixed_yaml", "pr_title", "pr_description"}
                missing = required_keys - set(parsed.keys())
                if missing:
                    raise ValueError(f"Bedrock response missing keys: {missing}")

                return parsed

            except self._client.exceptions.ThrottlingException as exc:
                last_exception = exc
                if attempt < max_retries:
                    wait = 2 ** (attempt + 1)
                    time.sleep(wait)
                    continue
                raise

            except (json.JSONDecodeError, ValueError, KeyError) as exc:
                _raw = locals().get("raw_text", "<unavailable>")
                raise RuntimeError(
                    f"Failed to parse Bedrock response as valid JSON: {exc}\n"
                    f"Raw response: {_raw}"
                ) from exc

        raise RuntimeError("Bedrock invocation failed after retries") from last_exception
